# ------------------------------------------------------------
# PlatformIO Project Configuration
# ------------------------------------------------------------
# esp32dev : flash firmware to the ESP32 over USB
# native   : compile and run locally on PC (no hardware needed)
# ------------------------------------------------------------

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200  ; match Serial.begin(115200) in main.cpp

[env:native]
platform = native
build_flags = -std=c++17
